### ISSUE TITLE
Проглатываются ошибки

### ISSUE THREAD

**Issue by mayorovp** [mayorovp/codegolf#10]
В случае возникновения ошибки эта самая ошибка проглатывается обещанием без всяких сообщений пользователю.

**Comment by urffin** [comment]
Добавил catch на самый первый promise.
https://github.com/mayorovp/codegolf/commit/aa1a66f2aad99ec9773b15461e59d5787dbbcc1a

**Comment by mayorovp** [comment]
Отлично, больше ошибки не проглатываются.

**Comment by urffin** [comment]
@mayorovp, а как кстати ссылаться на issue в коммите, чтобы он автоматом привязывался?

**Comment by mayorovp** [comment]
@urffin  https://help.github.com/articles/closing-issues-via-commit-messages/
